name: Deploy Application to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
#          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      # Step 4: Initialize Terraform
      - name: Terraform init
        run: terraform init

      # Step 5: Plan Terraform deployment
      - name: Terraform plan
        run: terraform plan

      # Step 6: Apply Terraform configuration
      - name: Terraform apply
        run: terraform apply -auto-approve

      # Step 7: Test Load Balancer (public access)
      - name: Test Load Balancer
        run: |
          lb_url=$(aws elbv2 describe-load-balancers --names yhsllm-app-lb --query "LoadBalancers[0].DNSName" --output text)
          echo "Load Balancer URL: http://$lb_url"
          curl -I http://$lb_url

